### ISSUE TITLE
indentation 

### ISSUE THREAD

**Issue by aminmahrami** [ozgurleo/hyf-html-css#1]
https://github.com/ozgurleo/hyf-html-css/blob/4a2d43cd936db94cde21a614ccec3851a02635b7/week1/index.html#L3
As head is inside html so i needs one more tab . opening and closing tags also vertically should be in same line.

**Comment by aminmahrami** [comment]
https://github.com/ozgurleo/hyf-html-css/blob/4a2d43cd936db94cde21a614ccec3851a02635b7/week1/index.html#L16 
you don't need to wrap a `h2` in a `p` paragraph is unnecessary here because we have a list not sentences

**Comment by aminmahrami** [comment]
as you know you don't need a <nav> for every <a> nav is for navigation bar that has multiple links inside.

**Comment by ozgurleo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ozgur Aslan](https://trello.com/c/XHHvk5Ca/1724-ozgur-aslan)
